Theoretical Questions:

Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Answer :

NumPy, which stands for Numerical Python, is a fundamental library in Python for scientific computing and data analysis. Here are its key purposes and advantages:

### Purpose of NumPy

1. **Efficient Array Storage**: NumPy introduces the `ndarray` object, a powerful n-dimensional array that provides a way to store and manipulate large datasets efficiently.

2. **Numerical Operations**: It offers a wide range of mathematical functions and operations that can be performed on these arrays, making it ideal for numerical computing tasks.

3. **Interoperability**: NumPy serves as a foundational library for many other scientific computing libraries in Python, such as SciPy, Pandas, and Matplotlib.

### Advantages of NumPy

1. **Performance**: NumPy arrays are more memory-efficient and faster than Python lists, especially for large datasets. This is due to contiguous memory allocation and the fact that NumPy operations are implemented in C.

2. **Convenient Syntax**: NumPy provides a rich set of functions that allow for concise and readable code. Operations on arrays can be performed element-wise, which simplifies many mathematical computations.

3. **Broadcasting**: This powerful feature allows NumPy to perform operations on arrays of different shapes, automatically expanding dimensions as needed. This reduces the need for complex looping.

4. **Vectorization**: NumPy supports vectorized operations, which means you can apply functions to entire arrays without needing to write explicit loops. This leads to cleaner code and often improves performance.

5. **Mathematical Functions**: It includes a comprehensive collection of mathematical functions for linear algebra, statistics, Fourier transforms, and more, which are optimized for performance.

6. **Integration with C/C++ and Fortran**: NumPy allows for easy integration with low-level languages, enabling performance improvements and the use of existing libraries.

7. **Multi-dimensional Arrays**: It supports multi-dimensional arrays, enabling complex data structures and operations that are essential for many scientific applications.

### Enhancing Python's Capabilities

By providing these features, NumPy significantly enhances Python's capabilities for numerical operations:

- **Speed**: Operations that would be slow with native Python can be performed much faster with NumPy due to its optimized performance.
- **Simplicity**: It simplifies the code needed for complex mathematical computations, making it accessible to a wider audience.
- **Functionality**: The vast array of built-in functions allows for more sophisticated data analysis and scientific computing tasks without needing to implement everything from scratch.

Overall, NumPy is a cornerstone of scientific computing in Python, providing essential tools that make data analysis and numerical computation efficient and straightforward.



2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Answer :
In NumPy, both `np.mean()` and `np.average()` are used to compute the average of an array, but they have some important differences in functionality and flexibility. Here’s a comparison of the two:

### `np.mean()`

- **Purpose**: Calculates the arithmetic mean (average) of an array.
- **Syntax**: `np.mean(a, axis=None, dtype=None, out=None)`
- **Parameters**:
  - `a`: Input array.
  - `axis`: Axis or axes along which to compute the mean. By default, the mean is computed over the flattened array.
  - `dtype`: Data type of the returned array.
  - `out`: Alternative output array to place the result.
- **Return Value**: The mean of the array elements.

### `np.average()`

- **Purpose**: Calculates the weighted average of an array.
- **Syntax**: `np.average(a, axis=None, weights=None, returned=False)`
- **Parameters**:
  - `a`: Input array.
  - `axis`: Axis or axes along which to compute the average.
  - `weights`: An array of weights the same shape as `a`. If provided, the average is computed as the weighted sum of the values divided by the sum of the weights.
  - `returned`: If `True`, returns a tuple containing the average and the sum of the weights.
- **Return Value**: The weighted average of the array elements (or a tuple if `returned=True`).

### Key Differences

1. **Weights**:
   - `np.mean()` does not accept weights. It computes a simple arithmetic mean.
   - `np.average()` allows for the specification of weights, enabling the calculation of a weighted average.

2. **Use Cases**:
   - Use `np.mean()` when you want a straightforward average of the data without any additional considerations.
   - Use `np.average()` when you need to take into account different weights for different elements in the array.

3. **Return Type**:
   - Both functions return a scalar or an array, depending on the input. However, `np.average()` can return additional information about the weights if `returned=True`.

### When to Use Each

- **Use `np.mean()`**:
  - When you want a simple average of the elements in an array.
  - When performance is a concern, as it’s generally faster for large datasets due to less overhead.

- **Use `np.average()`**:
  - When you have weights that should influence the average.
  - When you want additional information about the computation (e.g., the sum of weights).

### Example

```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])

# Simple mean
mean_value = np.mean(data)  # Output: 3.0

# Weighted average
weights = np.array([1, 1, 1, 1, 5])  # Heavier weight for the last element
weighted_average = np.average(data, weights=weights)  # Output: 4.0
```

In summary, choose `np.mean()` for basic averaging and `np.average()` when weights are involved.


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

answer:

Reversing a NumPy array can be accomplished using slicing or specific functions. Here’s how to reverse a NumPy array along different axes, with examples for both 1D and 2D arrays.

### 1D Array Reversal

For a 1D array, you can reverse the array using slicing.

#### Example:

```python
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the 1D array
reversed_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_1d)
```

**Output:**
```
Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]
```

### 2D Array Reversal

For a 2D array, you can reverse the array along specific axes using slicing.

#### Reversing along the First Axis (Rows)

This will reverse the order of the rows.

#### Example:

```python
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along the first axis (rows)
reversed_rows = arr_2d[::-1]

print("Original 2D array:\n", arr_2d)
print("Reversed 2D array (rows):\n", reversed_rows)
```

**Output:**
```
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D array (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
```

#### Reversing along the Second Axis (Columns)

This will reverse the order of the columns.

#### Example:

```python
# Reverse along the second axis (columns)
reversed_columns = arr_2d[:, ::-1]

print("Reversed 2D array (columns):\n", reversed_columns)
```

**Output:**
```
Reversed 2D array (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
```

### Summary of Methods

- **1D Array**: Use slicing `[::-1]` to reverse the array.
- **2D Array**:
  - To reverse along the first axis (rows): `arr_2d[::-1]`
  - To reverse along the second axis (columns): `arr_2d[:, ::-1]`

These techniques allow you to easily manipulate and reverse NumPy arrays along various axes, making data processing and analysis more flexible.

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Answer :

To determine the data type of elements in a NumPy array, you can use the `dtype` attribute of the array. Here’s how you can do it:

### Determining Data Type

#### Example:

```python
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Get the data type of the array elements
data_type = arr.dtype

print("Data type of array elements:", data_type)
```

**Output:**
```
Data type of array elements: int64
```

### Importance of Data Types

1. **Memory Management**:
   - Each data type in NumPy has a specific size in memory (e.g., `int32`, `int64`, `float32`, `float64`, etc.). Choosing the appropriate data type can significantly impact memory usage.
   - For instance, using `float32` instead of `float64` can halve the memory consumption when working with large arrays, which is critical in memory-constrained environments.

2. **Performance**:
   - Operations on smaller data types can be faster. For example, arithmetic operations on `int32` arrays are generally faster than on `int64` arrays due to less data being processed.
   - Using the correct data type can also enhance performance in calculations, especially when leveraging NumPy’s optimized routines that can take advantage of specific data types.

3. **Type Safety**:
   - Specifying the data type helps ensure that operations are performed correctly. For example, using `int` types prevents accidental floating-point operations that could lead to unintended results.

4. **Interoperability**:
   - When interfacing with other libraries (like SciPy or Pandas), consistent data types can prevent issues related to type mismatches, making the code more robust and easier to maintain.

### Changing Data Types

You can also change the data type of an existing array using the `astype()` method:

#### Example:

```python
# Convert the array to float
arr_float = arr.astype(np.float32)

print("Original data type:", arr.dtype)
print("Converted data type:", arr_float.dtype)
```

**Output:**
```
Original data type: int64
Converted data type: float32
```


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Answer:

In NumPy, **ndarrays** (n-dimensional arrays) are the core data structure used to store and manipulate numerical data. They are central to the functionality of NumPy and provide a powerful way to handle large datasets.

### Key Features of ndarrays

1. **Homogeneous Data Type**: 
   - All elements in an ndarray must be of the same data type (e.g., integers, floats). This is unlike Python lists, which can contain mixed data types.

2. **Multidimensional**: 
   - ndarrays can be 1D, 2D, or even higher-dimensional (n-dimensional). This flexibility allows for the representation of scalars, vectors, matrices, and tensors.

3. **Efficient Memory Storage**: 
   - ndarrays use contiguous blocks of memory, which leads to more efficient storage and better performance compared to Python lists. This makes operations on ndarrays faster.

4. **Vectorized Operations**: 
   - NumPy allows for element-wise operations on ndarrays without the need for explicit loops. This vectorization significantly improves performance and makes code more concise.

5. **Broadcasting**: 
   - ndarrays support broadcasting, which allows for operations on arrays of different shapes. This means you can perform arithmetic operations on arrays of different sizes without needing to reshape them explicitly.

6. **Advanced Indexing and Slicing**: 
   - ndarrays offer more powerful indexing and slicing options compared to Python lists. You can index with arrays, use boolean indexing, and select sub-arrays easily.

7. **Built-in Mathematical Functions**: 
   - NumPy provides a wide range of built-in functions for mathematical operations (e.g., sum, mean, max) that are optimized for performance.

### Differences from Standard Python Lists

1. **Data Type**:
   - **ndarrays**: Homogeneous (same data type).
   - **Python Lists**: Heterogeneous (can contain mixed data types).

2. **Performance**:
   - **ndarrays**: Faster for numerical operations due to optimized C implementations and contiguous memory allocation.
   - **Python Lists**: Slower for numerical tasks, as they require loops and are less memory-efficient.

3. **Dimension**:
   - **ndarrays**: Can easily handle multidimensional data (e.g., matrices, tensors).
   - **Python Lists**: Can be nested to create multidimensional structures, but it's less efficient and more cumbersome.

4. **Functionality**:
   - **ndarrays**: Offer extensive mathematical and statistical functions, as well as advanced indexing capabilities.
   - **Python Lists**: Basic data structure without specialized numerical methods.

5. **Memory Management**:
   - **ndarrays**: More efficient memory usage, leading to lower overhead when handling large datasets.
   - **Python Lists**: Higher overhead due to object references and flexibility in data types.

### Example of ndarrays vs. Python Lists

#### Using a Python List:

```python
# Create a Python list
py_list = [1, 2, 3, 4, 5]

# Performing an operation requires a loop
squared_list = [x**2 for x in py_list]
```

#### Using a NumPy ndarray:

```python
import numpy as np

# Create a NumPy ndarray
np_array = np.array([1, 2, 3, 4, 5])

# Vectorized operation
squared_array = np_array**2
```

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Answwer :

NumPy arrays offer several performance benefits over Python lists for large-scale numerical operations:

1. **Memory Efficiency**: 
   - NumPy arrays store data in contiguous memory blocks, reducing overhead and allowing for more efficient use of memory compared to the more fragmented memory allocation of Python lists.

2. **Speed**:
   - Operations on NumPy arrays are implemented in C, enabling faster execution of mathematical computations. This is particularly noticeable for large datasets where vectorized operations can significantly outperform Python loops.

3. **Vectorization**:
   - NumPy allows element-wise operations directly on entire arrays without explicit loops, leading to cleaner code and faster execution. This reduces the execution time for bulk operations.

4. **Broadcasting**:
   - NumPy supports broadcasting, allowing for operations on arrays of different shapes without needing to manually reshape them. This leads to more efficient and concise code.

5. **Optimized Mathematical Functions**:
   - NumPy provides a range of optimized built-in mathematical functions that are faster than applying the same operations using Python list comprehensions.

### Conclusion

Overall, the combination of optimized memory usage, faster execution, and advanced functionality makes NumPy arrays far superior to Python lists for large-scale numerical operations, especially in scientific computing and data analysis contexts.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Answer :

In NumPy, `vstack()` and `hstack()` are functions used to stack arrays vertically and horizontally, respectively.

### `vstack()`
- **Function**: Stacks arrays in sequence vertically (row-wise).
- **Usage**: `np.vstack(tup)`
- **Input**: A tuple of arrays with the same shape along all but the first axis.

#### Example:

```python
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                  [10, 11, 12]])

# Vertical stacking
vstacked = np.vstack((arr1, arr2))

print("vstack output:\n", vstacked)
```

**Output:**
```
vstack output:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
```

### `hstack()`
- **Function**: Stacks arrays in sequence horizontally (column-wise).
- **Usage**: `np.hstack(tup)`
- **Input**: A tuple of arrays with the same shape along all but the second axis.

#### Example:

```python
# Horizontal stacking
hstacked = np.hstack((arr1, arr2))

print("hstack output:\n", hstacked)
```

**Output:**
```
hstack output:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
```

### Summary
- **`vstack()`**: Combines arrays vertically, increasing the number of rows.
- **`hstack()`**: Combines arrays horizontally, increasing the number of columns.

These functions are essential for efficiently combining arrays in different orientations in NumPy.

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Answer :

In NumPy, `fliplr()` and `flipud()` are methods used to flip arrays along specific axes:

### `fliplr()`
- **Function**: Flips an array left to right (horizontal flip).
- **Effect**: Reverses the order of columns.
- **Applicable Dimensions**: Primarily works on 2D arrays, but can be applied to higher dimensions by treating them as 2D for the operation.

#### Example:
```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flipped_lr = np.fliplr(arr)

print("Original Array:\n", arr)
print("Flipped Left to Right:\n", flipped_lr)
```

**Output:**
```
Original Array:
 [[1 2 3]
 [4 5 6]]
Flipped Left to Right:
 [[3 2 1]
 [6 5 4]]
```

### `flipud()`
- **Function**: Flips an array upside down (vertical flip).
- **Effect**: Reverses the order of rows.
- **Applicable Dimensions**: Primarily works on 2D arrays, but can also be applied to higher dimensions by treating them as 2D for the operation.

#### Example:
```python
flipped_ud = np.flipud(arr)

print("Flipped Up to Down:\n", flipped_ud)
```

**Output:**
```
Flipped Up to Down:
 [[4 5 6]
 [1 2 3]]
```

### Summary of Differences
- **`fliplr()`**: Flips columns, affecting the horizontal layout.
- **`flipud()`**: Flips rows, affecting the vertical layout.

Both methods are useful for manipulating array orientations in NumPy, particularly for image processing or data transformations.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Answer:

The `array_split()` method in NumPy is used to divide an array into multiple sub-arrays. It can split an array either evenly or at specified indices, providing flexibility in data manipulation.

### Functionality

- **Syntax**: `numpy.array_split(ary, indices_or_sections, axis=0)`
  - **ary**: The input array.
  - **indices_or_sections**: An integer for the number of splits or an array of indices for custom splits.
  - **axis**: The axis along which to split (default is 0).

### Handling Uneven Splits

When the array cannot be divided evenly (e.g., 7 elements into 3 splits), `array_split()` handles this by distributing the remaining elements among the first few sub-arrays. 

For example, splitting an array of 7 elements into 3 parts might yield sub-arrays with sizes [3, 2, 2].

### Example

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split into 3 parts
split_arrays = np.array_split(arr, 3)

print(split_arrays)
```

**Output:**
```
[array([1, 2, 3]), array([4, 5]), array([6, 7])]
```

### Summary

`array_split()` is a versatile function for splitting arrays, effectively handling uneven splits by distributing extra elements across the resulting sub-arrays.


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Answer :

### Vectorization

**Vectorization** in NumPy refers to the ability to perform operations on entire arrays without the need for explicit loops. Instead of iterating through each element, operations are applied simultaneously across the entire array, leveraging low-level optimizations.

#### Benefits:
- **Performance**: Vectorized operations are executed in compiled C code, making them significantly faster than Python loops.
- **Conciseness**: Code is cleaner and easier to read, as it reduces the complexity of manual iteration.

**Example**:
```python
import numpy as np

arr = np.array([1, 2, 3, 4])
squared = arr ** 2  # Vectorized operation
```

### Broadcasting

**Broadcasting** allows NumPy to perform operations on arrays of different shapes. It automatically expands the dimensions of smaller arrays to match the larger array's shape without actually copying data.

#### Rules:
1. If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on the left.
2. The sizes of the dimensions must either be the same or one of them must be 1.

#### Benefits:
- **Flexibility**: Operations can be performed between arrays of different shapes, simplifying many mathematical operations.
- **Memory Efficiency**: Broadcasting avoids the need to create large intermediate arrays, saving memory.

**Example**:
```python
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2  # Broadcasting arr2 across arr1
```

### Contribution to Efficient Array Operations

Both vectorization and broadcasting contribute to efficient array operations by:

- **Reducing Execution Time**: They minimize the overhead associated with Python loops and enable faster computation through optimized C routines.
- **Simplifying Code**: They allow for more intuitive and readable code, making it easier to implement complex mathematical operations without extensive boilerplate.
- **Memory Optimization**: They enhance memory usage by avoiding unnecessary data duplication, particularly in broadcasting scenarios.

In summary, vectorization and broadcasting are key features of NumPy that greatly enhance the performance and efficiency of numerical operations, making it a powerful tool for scientific computing and data analysis.

Practical Questions:

In [6]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:\n", transposed_array)


Original Array:
 [[69 25 94]
 [63 77 87]
 [65 22 37]]

Transposed Array:
 [[69 63 65]
 [25 77 22]
 [94 87 37]]


In [8]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # Creates an array with values from 0 to 9
print("Original 1D Array:\n", array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped 2x5 Array:\n", array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped 5x2 Array:\n", array_5x2)


Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", array_4x4)

# Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:\n", array_with_border)


Original 4x4 Array:
 [[0.77553311 0.33500868 0.22775503 0.38793348]
 [0.85713519 0.71472392 0.18005426 0.35825701]
 [0.1478141  0.36246311 0.53748417 0.53075331]
 [0.84657561 0.01859127 0.08149742 0.50856955]]

6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.77553311 0.33500868 0.22775503 0.38793348 0.        ]
 [0.         0.85713519 0.71472392 0.18005426 0.35825701 0.        ]
 [0.         0.1478141  0.36246311 0.53748417 0.53075331 0.        ]
 [0.         0.84657561 0.01859127 0.08149742 0.50856955 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [12]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array from 10 to 60 with step of 5:\n", array)


Array from 10 to 60 with step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [14]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(array)
lower_case = np.char.lower(array)
title_case = np.char.title(array)
capitalize_case = np.char.capitalize(array)

# Display the results
print("Original Array:\n", array)
print("\nUpper Case:\n", upper_case)
print("\nLower Case:\n", lower_case)
print("\nTitle Case:\n", title_case)
print("\nCapitalize Case:\n", capitalize_case)


Original Array:
 ['python' 'numpy' 'pandas']

Upper Case:
 ['PYTHON' 'NUMPY' 'PANDAS']

Lower Case:
 ['python' 'numpy' 'pandas']

Title Case:
 ['Python' 'Numpy' 'Pandas']

Capitalize Case:
 ['Python' 'Numpy' 'Pandas']


In [16]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Display the results
print("Original Array:\n", words_array)
print("\nArray with Spaces Between Characters:\n", spaced_words)


Original Array:
 ['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
 ['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


In [18]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Display the results
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)

print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [20]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [22]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Random Integers:\n", random_integers)

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the prime numbers
print("\nPrime Numbers in the Array:\n", prime_numbers)


Random Integers:
 [203 404 212 178 474 442 260 755 897 544 982 809 338 254 300 397 432 412
  59 530 291 947 489 263 256 401 833 532 986 801 476 102 201 200 395 138
 609 446 166 229 966 575 158 735 544 887 478 470 572 258 501 202 862 254
 971 420 541 537 409 227  53 668 813 390 663 873 838 235 537 344 914 455
 288   9 426 425 273 944 195 560 257 206 934 494 360 334 271 686 215 231
 731 188 391 969 341  71 943 939 783 394]

Prime Numbers in the Array:
 [809, 397, 59, 947, 263, 401, 229, 887, 971, 541, 409, 227, 53, 257, 271, 71]


In [28]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 31, size=30)
print("Daily Temperatures for the Month:\n", daily_temperatures)

# Reshape the array into a 2D array with 5 weeks (6 days each for the first four weeks, and 6 days for the last week)
weekly_temperatures = daily_temperatures.reshape(5, 6)

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the weekly averages
print("\nWeekly Averages:\n", weekly_averages)


Daily Temperatures for the Month:
 [23 30 21 20 21 28 22 19 23 15 18 28 24 28 30 29 30 15 19 19 24 16 17 15
 21 17 24 24 18 28]

Weekly Averages:
 [23.83333333 20.83333333 26.         18.33333333 22.        ]
